let navBar=document.getElementById("navBar")
        navBar.setAttribute("id","socialNetworkNavigation")
        let newli=document.createElement("li")
        let text=document.createTextNode("logout")
        newli.appendChild(text)
        let ul=document.querySelector("#socialNetworkNavigation ul")
        ul.appendChild(newli)
        console.log("first link",ul.firstElementChild.textContent)
        console.log("last",ul.lastElementChild)