-- CREATE TABLE actors (
--     id SERIAL PRIMARY KEY,
--     first_name VARCHAR(50) NOT NULL,
--     last_name VARCHAR(50) NOT NULL,
--     birth_date DATE
-- );
-- SELECT COUNT(*) FROM actors;
-- INSERT INTO actors (first_name, last_name, birth_date) 
-- VALUES ('', '', NULL);
-- SELECT column_name, is_nullable 
-- FROM information_schema.columns 
-- WHERE table_name = 'actors';

